# Generated by Django 3.2.25 on 2024-06-13 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('origem', models.CharField(choices=[('PT', 'Exame Nacional Português'), ('BR', 'ENEM Brasil'), ('SUPERIOR', 'Nível Superior')], max_length=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('texto', models.TextField()),
                ('gabarito', models.CharField(max_length=200)),
                ('dificuldade', models.CharField(choices=[('FACIL', 'Fácil'), ('MEDIO', 'Médio'), ('DIFICIL', 'Difícil')], max_length=10)),
                ('imagem', models.BooleanField(default=False)),
                ('link_imagem', models.URLField(blank=True, null=True)),
                ('assunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questoes.assunto')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questoes.disciplina')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='assunto',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assuntos', to='questoes.disciplina'),
        ),
    ]
