# Generated by Django 3.2.25 on 2024-06-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='latex_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
