# Generated by Django 3.2.25 on 2024-06-15 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0002_questao_latex_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questao',
            name='texto',
        ),
    ]
