# Generated by Django 3.2.25 on 2024-08-26 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0003_remove_questao_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='math_jax',
            field=models.TextField(blank=True, null=True),
        ),
    ]
