# Generated by Django 3.2.25 on 2024-08-26 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0004_questao_math_jax'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='link_bucket',
            field=models.URLField(blank=True, null=True),
        ),
    ]
